export const ANSWERS = Object.freeze({
  en: [
    { id: "c01", category: "COMMON", text: "Probably, but the evidence is still loading." },
    { id: "c02", category: "COMMON", text: "The frog requests a second opinion." },
    { id: "c03", category: "COMMON", text: "Not today. You merely look suspicious." },
    { id: "c04", category: "COMMON", text: "Your last decision did not help your case." },
    { id: "c05", category: "COMMON", text: "Intelligence detected. Signal extremely weak." },
    { id: "c06", category: "COMMON", text: "The council is confused, but optimistic." },
    { id: "c07", category: "COMMON", text: "You are not an idiot. You are an unscheduled experiment." },
    { id: "c08", category: "COMMON", text: "Ask again after pretending to think first." },
    { id: "c09", category: "COMMON", text: "No. That was simply premium-grade nonsense." },
    { id: "c10", category: "COMMON", text: "The frog says your warranty is still valid." },
    { id: "c11", category: "COMMON", text: "You pass, but only because the test was upside down." },
    { id: "c12", category: "COMMON", text: "Your brain is on a scheduled coffee break." },
    { id: "c13", category: "COMMON", text: "Results inconclusive. Please reboot your common sense." },
    { id: "c14", category: "COMMON", text: "You are operating within normal human silliness." },
    { id: "c15", category: "COMMON", text: "The answer is hidden behind a loading spinner." },
    { id: "c16", category: "COMMON", text: "Maybe. The frog forgot the question halfway through." },
    { id: "c17", category: "COMMON", text: "Your cleverness is currently in airplane mode." },
    { id: "c18", category: "COMMON", text: "The situation is silly. You remain under investigation." },
    { id: "c19", category: "COMMON", text: "You are fine. The plan, however, needs supervision." },
    { id: "c20", category: "COMMON", text: "A harmless amount of idiot energy has been detected." },
    { id: "c21", category: "COMMON", text: "The frog sees potential. It refuses to say what kind." },
    { id: "c22", category: "COMMON", text: "Your thought process took the scenic route." },
    { id: "c23", category: "COMMON", text: "You are not wrong. Reality is being difficult." },
    { id: "c24", category: "COMMON", text: "Your idea has character. Accuracy was not invited." },
    { id: "c25", category: "COMMON", text: "The frog nods politely and changes the subject." },
    { id: "c26", category: "COMMON", text: "Your brain has 37 tabs open and music playing somewhere." },
    { id: "c27", category: "COMMON", text: "No idiot found. Check again after your next purchase." },
    { id: "c28", category: "COMMON", text: "You are temporarily exempt due to low expectations." },
    { id: "c29", category: "COMMON", text: "That was not stupidity. It was experimental decision-making." },
    { id: "c30", category: "COMMON", text: "The frog cannot judge you while laughing this hard." },
    { id: "c31", category: "COMMON", text: "Your logic arrived safely. Your conclusion missed the bus." },
    { id: "c32", category: "COMMON", text: "You appear mostly functional from this distance." },
    { id: "c33", category: "COMMON", text: "The verdict is maybe, with decorative confidence." },
    { id: "c34", category: "COMMON", text: "You have been cleared of intentional intelligence." },
    { id: "c35", category: "COMMON", text: "The frog believes in you, for tax purposes." },
    { id: "n01", category: "SNARKY", text: "You opened this website voluntarily. Let us begin there." },
    { id: "n02", category: "SNARKY", text: "The frog had faith in you. Past tense." },
    { id: "n03", category: "SNARKY", text: "Your brain has entered energy-saving mode." },
    { id: "n04", category: "SNARKY", text: "You are thinking outside the box because you lost the box." },
    { id: "n05", category: "SNARKY", text: "That was a brave decision for someone without a plan." },
    { id: "n06", category: "SNARKY", text: "Even your imaginary advisor just resigned." },
    { id: "n07", category: "SNARKY", text: "You appear to be buffering in real life." },
    { id: "n08", category: "SNARKY", text: "Your common sense has left the group chat." },
    { id: "n09", category: "SNARKY", text: "You brought confidence to a knowledge fight." },
    { id: "n10", category: "SNARKY", text: "The plan was flawless until it encountered reality." },
    { id: "n11", category: "SNARKY", text: "Your internal compass is sponsored by chaos." },
    { id: "n12", category: "SNARKY", text: "You have mistaken enthusiasm for preparation again." },
    { id: "n13", category: "SNARKY", text: "The frog checked your sources. They were vibes." },
    { id: "n14", category: "SNARKY", text: "You skipped step one and invented step seven." },
    { id: "n15", category: "SNARKY", text: "Your backup plan is just the original plan wearing a hat." },
    { id: "n16", category: "SNARKY", text: "That explanation raised more questions than it buried." },
    { id: "n17", category: "SNARKY", text: "You are one confident click away from a tutorial." },
    { id: "n18", category: "SNARKY", text: "The frog recommends reading the button before pressing it." },
    { id: "n19", category: "SNARKY", text: "Your logic is technically present and emotionally unavailable." },
    { id: "n20", category: "SNARKY", text: "You solved the wrong problem with impressive dedication." },
    { id: "n21", category: "SNARKY", text: "Your decision tree is more of a decorative shrub." },
    { id: "n22", category: "SNARKY", text: "The evidence is clear. Unfortunately, you ignored it." },
    { id: "n23", category: "SNARKY", text: "You did your own research and frightened the research." },
    { id: "n24", category: "SNARKY", text: "Your confidence is doing unpaid overtime." },
    { id: "n25", category: "SNARKY", text: "The frog says congratulations on almost noticing the obvious." },
    { id: "n26", category: "SNARKY", text: "Your brain saw the warning label and treated it like a challenge." },
    { id: "n27", category: "SNARKY", text: "You did not miss the point. You launched it into another timezone." },
    { id: "n28", category: "SNARKY", text: "The frog asked for your reasoning. You submitted a shrug." },
    { id: "n29", category: "SNARKY", text: "Your brain clicked remind me later on reality." },
    { id: "n30", category: "SNARKY", text: "Even autocorrect refuses to take responsibility for that decision." },
    { id: "n31", category: "SNARKY", text: "You are not thinking outside the box. You are arguing with the packaging." },
    { id: "n32", category: "SNARKY", text: "You make hindsight look like advanced technology." },
    { id: "n33", category: "SNARKY", text: "Your logic has been discontinued due to lack of demand." },
    { id: "n34", category: "SNARKY", text: "The frog has seen better planning from a browser with forty pop-ups." },
    { id: "n35", category: "SNARKY", text: "You entered the maze, ignored the map, and blamed the walls." },
    { id: "n36", category: "SNARKY", text: "Your common sense is currently listed as missing." },
    { id: "n37", category: "SNARKY", text: "You are the human version of clicking accept without reading anything." },
    { id: "s01", category: "SAVAGE", text: "You are the reason instructions include pictures." },
    { id: "s02", category: "SAVAGE", text: "Your strategy has all the structural integrity of wet bread." },
    { id: "s03", category: "SAVAGE", text: "The frog reviewed your choices and requested hazard pay." },
    { id: "s04", category: "SAVAGE", text: "You do not make mistakes. You create extended cinematic universes." },
    { id: "s05", category: "SAVAGE", text: "Your train of thought has been replaced by a bus service." },
    { id: "s06", category: "SAVAGE", text: "You have successfully failed the tutorial." },
    { id: "s07", category: "SAVAGE", text: "The universe gave you free will and immediately regretted the feature." },
    { id: "s08", category: "SAVAGE", text: "You could confuse a compass by standing still." },
    { id: "s09", category: "SAVAGE", text: "Your plan has fewer working parts than a broken spoon." },
    { id: "s10", category: "SAVAGE", text: "The frog found your logic in the lost-and-found. Nobody claimed it." },
    { id: "s11", category: "SAVAGE", text: "You turned a simple problem into downloadable content." },
    { id: "s12", category: "SAVAGE", text: "Your good idea escaped before you could explain it." },
    { id: "s13", category: "SAVAGE", text: "You are speedrunning consequences with no map." },
    { id: "s14", category: "SAVAGE", text: "Your brain submitted the assignment in the wrong file format." },
    { id: "s15", category: "SAVAGE", text: "You bring a unique perspective: consistently from the wrong direction." },
    { id: "s16", category: "SAVAGE", text: "Your decision-making process is an escape room with no exit." },
    { id: "s17", category: "SAVAGE", text: "You have the confidence of a software update at the worst possible time." },
    { id: "s18", category: "SAVAGE", text: "The frog tried lowering the bar. You brought a shovel." },
    { id: "s19", category: "SAVAGE", text: "You could lose an argument with an automatic door." },
    { id: "s20", category: "SAVAGE", text: "Your last good idea has filed a missing-person report." },
    { id: "s21", category: "SAVAGE", text: "The frog found more strategy in a calculator with no batteries." },
    { id: "s22", category: "SAVAGE", text: "You somehow turned doing nothing into a multi-step failure." },
    { id: "s23", category: "SAVAGE", text: "Your decision had one job and still requested technical support." },
    { id: "s24", category: "SAVAGE", text: "You make simple problems feel like season finales." },
    { id: "s25", category: "SAVAGE", text: "The frog lowered its expectations and heard a basement door open." },
    { id: "s26", category: "SAVAGE", text: "You have the rare talent of reaching the wrong answer from every direction." },
    { id: "s27", category: "SAVAGE", text: "Your plan was held together by confidence and one suspicious paper clip." },
    { id: "s28", category: "SAVAGE", text: "You are what happens when the tutorial is skipped with enthusiasm." },
    { id: "s29", category: "SAVAGE", text: "The frog tried to follow your logic and needed roadside assistance." },
    { id: "s30", category: "SAVAGE", text: "You did not just choose the wrong option. You invented a worse one." },
    { id: "t01", category: "RARE_TRUTH", text: "Making one bad decision does not make you an idiot. Refusing to examine it might. Learn what happened, change the pattern, and continue." },
    { id: "t02", category: "RARE_TRUTH", text: "Intelligence is not the absence of mistakes. It is the ability to notice them before pride turns them into habits." },
    { id: "t03", category: "RARE_TRUTH", text: "You may not need an insult. You may need more information, more patience, or the courage to admit that your first idea was wrong." },
    { id: "t04", category: "RARE_TRUTH", text: "A foolish moment is temporary. Building your identity around it is optional." },
    { id: "t05", category: "RARE_TRUTH", text: "Questioning yourself is usually evidence of self-awareness. Just do not let self-awareness become endless self-punishment." },
    { id: "t06", category: "RARE_TRUTH", text: "Before calling yourself stupid, ask whether you were tired, rushed, uninformed, afraid, or trying something difficult for the first time." },
    { id: "t07", category: "RARE_TRUTH", text: "A smart person can defend a bad idea for a very long time. Wisdom begins when being correct matters more than looking correct." },
    { id: "t08", category: "RARE_TRUTH", text: "You are allowed to change your mind when the evidence changes. That is not weakness; it is maintenance." },
    { id: "t09", category: "RARE_TRUTH", text: "Embarrassment is often the price of learning in public. Pay it once, keep the lesson, and move forward." },
    { id: "t10", category: "RARE_TRUTH", text: "The useful question is not whether you looked foolish. It is whether you understand enough now to choose differently next time." },
    { id: "t11", category: "RARE_TRUTH", text: "Confidence without curiosity becomes arrogance. Curiosity without action becomes avoidance. You need a little of both." },
    { id: "t12", category: "RARE_TRUTH", text: "Sometimes the mature response is simply: I did not know, I was wrong, and I will fix what I can." },
    { id: "f01", category: "FATAL", text: "The frog has reached a final conclusion." },
    { id: "f02", category: "FATAL", text: "Your trial period for common sense has expired." },
    { id: "f03", category: "FATAL", text: "The oracle has selected permanent relocation." },
    { id: "f04", category: "FATAL", text: "This result cannot be appealed." },
    { id: "f05", category: "FATAL", text: "Intelligence not found. Removing observer." },
    { id: "f06", category: "FATAL", text: "The frog reviewed your choices and selected the emergency exit." },
    { id: "f07", category: "FATAL", text: "Common sense has left the building. You are still inside." },
    { id: "f08", category: "FATAL", text: "The oracle found no recoverable decision-making data." }
  ],
  es: [
    { id: "c01", category: "COMMON", text: "Probablemente, pero la evidencia aún se está cargando." },
    { id: "c02", category: "COMMON", text: "La rana solicita una segunda opinión." },
    { id: "c03", category: "COMMON", text: "Hoy no. Simplemente luces sospechoso." },
    { id: "c04", category: "COMMON", text: "Tu última decisión no ayudó a tu caso." },
    { id: "c05", category: "COMMON", text: "Inteligencia detectada. Señal extremadamente débil." },
    { id: "c06", category: "COMMON", text: "El consejo está confundido, pero optimista." },
    { id: "c07", category: "COMMON", text: "No eres un idiota. Eres un experimento no programado." },
    { id: "c08", category: "COMMON", text: "Pregunta de nuevo después de fingir que piensas primero." },
    { id: "c09", category: "COMMON", text: "No. Eso fue simplemente tontería de primera calidad." },
    { id: "c10", category: "COMMON", text: "La rana dice que tu garantía aún es válida." },
    { id: "c11", category: "COMMON", text: "Apruebas, pero solo porque el test estaba al revés." },
    { id: "c12", category: "COMMON", text: "Tu cerebro está en un receso programado para el café." },
    { id: "c13", category: "COMMON", text: "Resultados no concluyentes. Por favor reinicia tu sentido común." },
    { id: "c14", category: "COMMON", text: "Estás operando dentro de la tontería humana normal." },
    { id: "c15", category: "COMMON", text: "La respuesta está oculta tras una rueda de carga." },
    { id: "c16", category: "COMMON", text: "Tal vez. La rana olvidó la pregunta a la mitad." },
    { id: "c17", category: "COMMON", text: "Tu astucia está actualmente en modo avión." },
    { id: "c18", category: "COMMON", text: "La situación es tonta. Sigues bajo investigación." },
    { id: "c19", category: "COMMON", text: "Estás bien. El plan, sin embargo, necesita supervisión." },
    { id: "c20", category: "COMMON", text: "Se ha detectado una cantidad inofensiva de energía idiota." },
    { id: "c21", category: "COMMON", text: "La rana ve potencial. Se niega a decir de qué tipo." },
    { id: "c22", category: "COMMON", text: "Tu proceso de pensamiento tomó la ruta panorámica." },
    { id: "c23", category: "COMMON", text: "No te equivocas. La realidad está siendo difícil." },
    { id: "c24", category: "COMMON", text: "Tu idea tiene carácter. La precisión no fue invitada." },
    { id: "c25", category: "COMMON", text: "La rana asiente cortésmente y cambia de tema." },
    { id: "c26", category: "COMMON", text: "Tu cerebro tiene 37 pestañas abiertas y música sonando en alguna parte." },
    { id: "c27", category: "COMMON", text: "Ningún idiota encontrado. Vuelve a comprobar tras tu próxima compra." },
    { id: "c28", category: "COMMON", text: "Estás temporalmente exento debido a las bajas expectativas." },
    { id: "c29", category: "COMMON", text: "Eso no fue estupidez. Fue una toma de decisiones experimental." },
    { id: "c30", category: "COMMON", text: "La rana no puede juzgarte mientras se ríe tan fuerte." },
    { id: "c31", category: "COMMON", text: "Tu lógica llegó a salvo. Tu conclusión perdió el autobús." },
    { id: "c32", category: "COMMON", text: "Pareces en su mayor parte funcional desde esta distancia." },
    { id: "c33", category: "COMMON", text: "El veredicto es tal vez, con confianza decorativa." },
    { id: "c34", category: "COMMON", text: "Has sido absuelto de inteligencia intencional." },
    { id: "c35", category: "COMMON", text: "La rana cree en ti, por motivos fiscales." },
    { id: "n01", category: "SNARKY", text: "Abriste este sitio web voluntariamente. Empecemos por ahí." },
    { id: "n02", category: "SNARKY", text: "La rana tenía fe en ti. En tiempo pasado." },
    { id: "n03", category: "SNARKY", text: "Tu cerebro ha entrado en modo ahorro de energía." },
    { id: "n04", category: "SNARKY", text: "Estás pensando fuera de la caja porque perdiste la caja." },
    { id: "n05", category: "SNARKY", text: "Esa fue una decisión valiente para alguien sin un plan." },
    { id: "n06", category: "SNARKY", text: "Incluso tu consejero imaginario acaba de renunciar." },
    { id: "n07", category: "SNARKY", text: "Parece que estás en estado de 'cargando' en la vida real." },
    { id: "n08", category: "SNARKY", text: "Tu sentido común ha abandonado el chat grupal." },
    { id: "n09", category: "SNARKY", text: "Llevaste confianza a una pelea de conocimientos." },
    { id: "n10", category: "SNARKY", text: "El plan era perfecto hasta que se topó con la realidad." },
    { id: "n11", category: "SNARKY", text: "Tu brújula interna está patrocinada por el caos." },
    { id: "n12", category: "SNARKY", text: "Has confundido entusiasmo con preparación de nuevo." },
    { id: "n13", category: "SNARKY", text: "La rana verificó tus fuentes. Eran solo vibras." },
    { id: "n14", category: "SNARKY", text: "Te saltaste el paso uno e inventaste el paso siete." },
    { id: "n15", category: "SNARKY", text: "Tu plan B es solo el plan original con un sombrero." },
    { id: "n16", category: "SNARKY", text: "Esa explicación generó más preguntas de las que enterró." },
    { id: "n17", category: "SNARKY", text: "Estás a un clic de confianza de necesitar un tutorial." },
    { id: "n18", category: "SNARKY", text: "La rana recomienda leer el botón antes de presionarlo." },
    { id: "n19", category: "SNARKY", text: "Tu lógica está técnicamente presente y emocionalmente indisponible." },
    { id: "n20", category: "SNARKY", text: "Resolviste el problema equivocado con una dedicación impresionante." },
    { id: "n21", category: "SNARKY", text: "Tu árbol de decisiones es más bien un arbusto decorativo." },
    { id: "n22", category: "SNARKY", text: "La evidencia es clara. Desafortunadamente, la ignoraste." },
    { id: "n23", category: "SNARKY", text: "Hiciste tu propia investigación y asustaste a la investigación." },
    { id: "n24", category: "SNARKY", text: "Tu confianza está haciendo horas extras sin paga." },
    { id: "n25", category: "SNARKY", text: "La rana te felicita por casi notar lo obvio." },
    { id: "n26", category: "SNARKY", text: "Tu cerebro vio la etiqueta de advertencia y la trató como un reto." },
    { id: "n27", category: "SNARKY", text: "No solo te perdiste el punto. Lo lanzaste a otra zona horaria." },
    { id: "n28", category: "SNARKY", text: "La rana pidió tu razonamiento. Entregaste un encogimiento de hombros." },
    { id: "n29", category: "SNARKY", text: "Tu cerebro hizo clic en 'recordármelo más tarde' sobre la realidad." },
    { id: "n30", category: "SNARKY", text: "Incluso el autocorrector se niega a asumir la responsabilidad por esa decisión." },
    { id: "n31", category: "SNARKY", text: "No estás pensando fuera de la caja. Estás discutiendo con el embalaje." },
    { id: "n32", category: "SNARKY", text: "Haces que mirar en retrospectiva parezca tecnología avanzada." },
    { id: "n33", category: "SNARKY", text: "Tu lógica ha sido descontinuada por falta de demanda." },
    { id: "n34", category: "SNARKY", text: "La rana ha visto mejor planificación en un navegador con cuarenta ventanas emergentes." },
    { id: "n35", category: "SNARKY", text: "Entraste al laberinto, ignoraste el mapa y culpaste a las paredes." },
    { id: "n36", category: "SNARKY", text: "Tu sentido común figura actualmente como desaparecido." },
    { id: "n37", category: "SNARKY", text: "Eres la versión humana de hacer clic en 'aceptar' sin leer nada." },
    { id: "s01", category: "SAVAGE", text: "Tú eres la razón por la que las instrucciones incluyen dibujos." },
    { id: "s02", category: "SAVAGE", text: "Tu estrategia tiene la misma integridad estructural que el pan mojado." },
    { id: "s03", category: "SAVAGE", text: "La rana revisó tus opciones y solicitó paga por riesgo." },
    { id: "s04", category: "SAVAGE", text: "No cometes errores. Creas universos cinematográficos extendidos." },
    { id: "s05", category: "SAVAGE", text: "Tu hilo de pensamiento ha sido reemplazado por un servicio de autobuses." },
    { id: "s06", category: "SAVAGE", text: "Has reprobado con éxito el tutorial." },
    { id: "s07", category: "SAVAGE", text: "El universo te dio libre albedrío e inmediatamente se arrepintió de la función." },
    { id: "s08", category: "SAVAGE", text: "Podrías confundir a una brújula estando quieto." },
    { id: "s09", category: "SAVAGE", text: "Tu plan tiene menos partes funcionales que una cuchara rota." },
    { id: "s10", category: "SAVAGE", text: "La rana encontró tu lógica en objetos perdidos. Nadie la reclamó." },
    { id: "s11", category: "SAVAGE", text: "Convertiste un problema sencillo en contenido descargable." },
    { id: "s12", category: "SAVAGE", text: "Tu buena idea escapó antes de que pudieras explicarla." },
    { id: "s13", category: "SAVAGE", text: "Estás haciendo un speedrun de las consecuencias sin mapa." },
    { id: "s14", category: "SAVAGE", text: "Tu cerebro entregó la tarea en el formato de archivo equivocado." },
    { id: "s15", category: "SAVAGE", text: "Aportas una perspectiva única: constantemente desde la dirección equivocada." },
    { id: "s16", category: "SAVAGE", text: "Tu proceso de decisión es un escape room sin salida." },
    { id: "s17", category: "SAVAGE", text: "Tienes la confianza de una actualización de software en el peor momento posible." },
    { id: "s18", category: "SAVAGE", text: "La rana intentó bajar el listón. Tú trajiste una pala." },
    { id: "s19", category: "SAVAGE", text: "Podrías perder una discusión con una puerta automática." },
    { id: "s20", category: "SAVAGE", text: "Tu última buena idea ha presentado una denuncia de desaparición." },
    { id: "s21", category: "SAVAGE", text: "La rana encontró más estrategia en una calculadora sin pilas." },
    { id: "s22", category: "SAVAGE", text: "De algún modo convertiste no hacer nada en un fracaso de múltiples pasos." },
    { id: "s23", category: "SAVAGE", text: "Tu decisión tenía un solo trabajo y aún así solicitó soporte técnico." },
    { id: "s24", category: "SAVAGE", text: "Haces que los problemas simples parezcan finales de temporada." },
    { id: "s25", category: "SAVAGE", text: "La rana bajó sus expectativas y escuchó abrirse la puerta de un sótano." },
    { id: "s26", category: "SAVAGE", text: "Tienes el raro talento de llegar a la respuesta equivocada desde todas las direcciones." },
    { id: "s27", category: "SAVAGE", text: "Tu plan se mantenía unido por la confianza y un sospechoso clip de papel." },
    { id: "s28", category: "SAVAGE", text: "Eres lo que sucede cuando se salta el tutorial con entusiasmo." },
    { id: "s29", category: "SAVAGE", text: "La rana intentó seguir tu lógica y necesitó asistencia en carretera." },
    { id: "s30", category: "SAVAGE", text: "No solo elegiste la opción equivocada. Inventaste una peor." },
    { id: "t01", category: "RARE_TRUTH", text: "Tomar una mala decisión no te convierte en idiota. Negarte a examinarla podría hacerlo. Aprende qué pasó, cambia el patrón y continúa." },
    { id: "t02", category: "RARE_TRUTH", text: "La inteligencia no es la ausencia de errores. Es la capacidad de notarlos antes de que el orgullo los convierta en hábitos." },
    { id: "t03", category: "RARE_TRUTH", text: "Puede que no necesites un insulto. Puede que necesites más información, más paciencia o el valor de admitir que tu primera idea estaba equivocada." },
    { id: "t04", category: "RARE_TRUTH", text: "Un momento de estupidez es temporal. Construir tu identidad en torno a ello es opcional." },
    { id: "t05", category: "RARE_TRUTH", text: "Cuestionarse a uno mismo suele ser evidencia de autoconciencia. Solo no dejes que la autoconciencia se convierta en un autocastigo interminable." },
    { id: "t06", category: "RARE_TRUTH", text: "Antes de llamarte estúpido, pregúntate si estabas cansado, apresurado, desinformado, asustado o intentando algo difícil por primera vez." },
    { id: "t07", category: "RARE_TRUTH", text: "Una persona inteligente puede defender una mala idea durante mucho tiempo. La sabiduría comienza cuando tener la razón importa más que parecer tenerla." },
    { id: "t08", category: "RARE_TRUTH", text: "Se te permite cambiar de opinión cuando la evidencia cambia. Eso no es debilidad; es mantenimiento." },
    { id: "t09", category: "RARE_TRUTH", text: "La vergüenza suele ser el precio de aprender en público. Paga una vez, quédate con la lección y sigue adelante." },
    { id: "t10", category: "RARE_TRUTH", text: "La pregunta útil no es si pareciste tonto. Es si ahora entiendes lo suficiente como para elegir de manera diferente la próxima vez." },
    { id: "t11", category: "RARE_TRUTH", text: "La confianza sin curiosidad se convierte en arrogancia. La curiosidad sin acción se convierte en evitación. Necesitas un poco de ambas." },
    { id: "t12", category: "RARE_TRUTH", text: "A veces la respuesta madura es simplemente: no lo sabía, me equivoqué y arreglaré lo que pueda." },
    { id: "f01", category: "FATAL", text: "La rana ha llegado a una conclusión final." },
    { id: "f02", category: "FATAL", text: "Tu período de prueba de sentido común ha expirado." },
    { id: "f03", category: "FATAL", text: "El oráculo ha seleccionado la reubicación permanente." },
    { id: "f04", category: "FATAL", text: "Este resultado no puede ser apelado." },
    { id: "f05", category: "FATAL", text: "Inteligencia no encontrada. Eliminando al observador." },
    { id: "f06", category: "FATAL", text: "La rana revisó tus opciones y seleccionó la salida de emergencia." },
    { id: "f07", category: "FATAL", text: "El sentido común ha abandonado el edificio. Tú sigues adentro." },
    { id: "f08", category: "FATAL", text: "El oráculo no encontró datos de toma de decisiones recuperables." }
  ],
  pt: [
    { id: "c01", category: "COMMON", text: "Provavelmente, mas as evidências ainda estão carregando." },
    { id: "c02", category: "COMMON", text: "O sapo solicita uma segunda opinião." },
    { id: "c03", category: "COMMON", text: "Hoje não. Você apenas parece suspeito." },
    { id: "c04", category: "COMMON", text: "Sua última decisão não ajudou no seu caso." },
    { id: "c05", category: "COMMON", text: "Inteligência detectada. Sinal extremamente fraco." },
    { id: "c06", category: "COMMON", text: "O conselho está confuso, mas otimista." },
    { id: "c07", category: "COMMON", text: "Você não é um idiota. Você é um experimento não programado." },
    { id: "c08", category: "COMMON", text: "Pergunte novamente depois de fingir que pensa primeiro." },
    { id: "c09", category: "COMMON", text: "Não. Isso foi simplesmente bobagem de primeira qualidade." },
    { id: "c10", category: "COMMON", text: "O sapo diz que sua garantia ainda é válida." },
    { id: "c11", category: "COMMON", text: "Você passou, mas só porque o teste estava de cabeça para baixo." },
    { id: "c12", category: "COMMON", text: "Seu cérebro está em uma pausa programada para o café." },
    { id: "c13", category: "COMMON", text: "Resultados inconclusivos. Por favor, reinicie seu bom senso." },
    { id: "c14", category: "COMMON", text: "Você está operando dentro da bobagem humana normal." },
    { id: "c15", category: "COMMON", text: "A resposta está escondida atrás de uma tela de carregamento." },
    { id: "c16", category: "COMMON", text: "Talvez. O sapo esqueceu a pergunta no meio do caminho." },
    { id: "c17", category: "COMMON", text: "Sua esperteza está atualmente no modo avião." },
    { id: "c18", category: "COMMON", text: "A situação é tola. Você permanece sob investigação." },
    { id: "c19", category: "COMMON", text: "Você está bem. O plano, no entanto, precisa de supervisão." },
    { id: "c20", category: "COMMON", text: "Uma quantidade inofensiva de energia idiota foi detectada." },
    { id: "c21", category: "COMMON", text: "O sapo vê potencial. Ele se recusa a dizer de que tipo." },
    { id: "c22", category: "COMMON", text: "Seu processo de pensamento pegou a rota cênica." },
    { id: "c23", category: "COMMON", text: "Você não está errado. A realidade está sendo difícil." },
    { id: "c24", category: "COMMON", text: "Sua ideia tem personalidade. A precisão não foi convidada." },
    { id: "c25", category: "COMMON", text: "O sapo assente educadamente e muda de assunto." },
    { id: "c26", category: "COMMON", text: "Seu cérebro tem 37 abas abertas e música tocando em algum lugar." },
    { id: "c27", category: "COMMON", text: "Nenhum idiota encontrado. Verifique novamente após a próxima compra." },
    { id: "c28", category: "COMMON", text: "Você está temporariamente isento devido às baixas expectativas." },
    { id: "c29", category: "COMMON", text: "Isso não foi estupidez. Foi uma tomada de decisão experimental." },
    { id: "c30", category: "COMMON", text: "O sapo não pode te julgar enquanto ri tão alto." },
    { id: "c31", category: "COMMON", text: "Sua lógica chegou em segurança. Sua conclusão perdeu o ônibus." },
    { id: "c32", category: "COMMON", text: "Você parece quase funcional dessa distância." },
    { id: "c33", category: "COMMON", text: "O veredito é talvez, com confiança decorativa." },
    { id: "c34", category: "COMMON", text: "Você foi inocentado de inteligência intencional." },
    { id: "c35", category: "COMMON", text: "O sapo acredita em você, para fins fiscais." },
    { id: "n01", category: "SNARKY", text: "Você abriu este site voluntariamente. Vamos começar por aí." },
    { id: "n02", category: "SNARKY", text: "O sapo tinha fé em você. No passado." },
    { id: "n03", category: "SNARKY", text: "Seu cérebro entrou no modo de economia de energia." },
    { id: "n04", category: "SNARKY", text: "Você está pensando fora da caixa porque perdeu a caixa." },
    { id: "n05", category: "SNARKY", text: "Foi uma decisão corajosa para alguém sem um plano." },
    { id: "n06", category: "SNARKY", text: "Até seu conselheiro imaginário acabou de se demitir." },
    { id: "n07", category: "SNARKY", text: "Você parece estar carregando na vida real." },
    { id: "n08", category: "SNARKY", text: "Seu bom senso saiu do grupo." },
    { id: "n09", category: "SNARKY", text: "Você trouxe confiança para uma briga de conhecimento." },
    { id: "n10", category: "SNARKY", text: "O plano era perfeito até encontrar a realidade." },
    { id: "n11", category: "SNARKY", text: "Sua bússola interna é patrocinada pelo caos." },
    { id: "n12", category: "SNARKY", text: "Você confundiu entusiasmo com preparação novamente." },
    { id: "n13", category: "SNARKY", text: "O sapo checou suas fontes. Eram apenas vibrações." },
    { id: "n14", category: "SNARKY", text: "Você pulou a etapa um e inventou a etapa sete." },
    { id: "n15", category: "SNARKY", text: "Seu plano B é apenas o plano original usando um chapéu." },
    { id: "n16", category: "SNARKY", text: "Essa explicação gerou mais perguntas do que enterrou." },
    { id: "n17", category: "SNARKY", text: "Você está a um clique confiante de um tutorial." },
    { id: "n18", category: "SNARKY", text: "O sapo recomenda ler o botão antes de pressioná-lo." },
    { id: "n19", category: "SNARKY", text: "Sua lógica está tecnicamente presente e emocionalmente indisponível." },
    { id: "n20", category: "SNARKY", text: "Você resolveu o problema errado com uma dedicação impressionante." },
    { id: "n21", category: "SNARKY", text: "Sua árvore de decisões é mais como um arbusto decorativo." },
    { id: "n22", category: "SNARKY", text: "A evidência é clara. Infelizmente, você a ignorou." },
    { id: "n23", category: "SNARKY", text: "Você fez sua própria pesquisa e assustou a pesquisa." },
    { id: "n24", category: "SNARKY", text: "Sua confiança está fazendo hora extra não remunerada." },
    { id: "n25", category: "SNARKY", text: "O sapo lhe dá os parabéns por quase notar o óbvio." },
    { id: "n26", category: "SNARKY", text: "Seu cérebro viu o aviso e o tratou como um desafio." },
    { id: "n27", category: "SNARKY", text: "Você não perdeu apenas o ponto. Você o lançou em outro fuso horário." },
    { id: "n28", category: "SNARKY", text: "O sapo pediu seu raciocínio. Você entregou um dar de ombros." },
    { id: "n29", category: "SNARKY", text: "Seu cérebro clicou em 'lembre-me mais tarde' na realidade." },
    { id: "n30", category: "SNARKY", text: "Até o corretor ortográfico se recusa a assumir a responsabilidade por essa decisão." },
    { id: "n31", category: "SNARKY", text: "Você não está pensando fora da caixa. Está discutindo com a embalagem." },
    { id: "n32", category: "SNARKY", text: "Você faz com que olhar em retrospectiva pareça tecnologia avançada." },
    { id: "n33", category: "SNARKY", text: "Sua lógica foi descontinuada por falta de demanda." },
    { id: "n34", category: "SNARKY", text: "O sapo já viu planejamento melhor em um navegador com quarenta pop-ups." },
    { id: "n35", category: "SNARKY", text: "Você entrou no labirinto, ignorou o mapa e culpou as paredes." },
    { id: "n36", category: "SNARKY", text: "Seu bom senso está listado como desaparecido no momento." },
    { id: "n37", category: "SNARKY", text: "Você é a versão humana de clicar em aceitar sem ler nada." },
    { id: "s01", category: "SAVAGE", text: "Você é o motivo pelo qual as instruções incluem desenhos." },
    { id: "s02", category: "SAVAGE", text: "Sua estratégia tem a integridade estrutural de um pão molhado." },
    { id: "s03", category: "SAVAGE", text: "O sapo revisou suas opções e solicitou adicional de periculosidade." },
    { id: "s04", category: "SAVAGE", text: "Você não comete erros. Você cria universos cinematográficos estendidos." },
    { id: "s05", category: "SAVAGE", text: "Sua linha de pensamento foi substituída por um serviço de ônibus." },
    { id: "s06", category: "SAVAGE", text: "Você falhou com sucesso no tutorial." },
    { id: "s07", category: "SAVAGE", text: "O universo lhe deu livre arbítrio e imediatamente se arrependeu do recurso." },
    { id: "s08", category: "SAVAGE", text: "Você poderia confundir uma bússola ficando parado." },
    { id: "s09", category: "SAVAGE", text: "Seu plano tem menos partes funcionando do que uma colher quebrada." },
    { id: "s10", category: "SAVAGE", text: "O sapo encontrou sua lógica nos achados e perdidos. Ninguém a reivindicou." },
    { id: "s11", category: "SAVAGE", text: "Você transformou um problema simples em conteúdo para download." },
    { id: "s12", category: "SAVAGE", text: "Sua boa ideia escapou antes que você pudesse explicá-la." },
    { id: "s13", category: "SAVAGE", text: "Você está fazendo um speedrun das consequências sem um mapa." },
    { id: "s14", category: "SAVAGE", text: "Seu cérebro enviou a tarefa no formato de arquivo errado." },
    { id: "s15", category: "SAVAGE", text: "Você traz uma perspectiva única: consistentemente da direção errada." },
    { id: "s16", category: "SAVAGE", text: "Seu processo de tomada de decisão é uma sala de fuga sem saída." },
    { id: "s17", category: "SAVAGE", text: "Você tem a confiança de uma atualização de software no pior momento possível." },
    { id: "s18", category: "SAVAGE", text: "O sapo tentou abaixar o nível. Você trouxe uma pá." },
    { id: "s19", category: "SAVAGE", text: "Você poderia perder uma discussão com uma porta automática." },
    { id: "s20", category: "SAVAGE", text: "Sua última boa ideia registrou um boletim de ocorrência de desaparecimento." },
    { id: "s21", category: "SAVAGE", text: "O sapo encontrou mais estratégia em uma calculadora sem pilhas." },
    { id: "s22", category: "SAVAGE", text: "Você de alguma forma transformou não fazer nada em um fracasso de várias etapas." },
    { id: "s23", category: "SAVAGE", text: "Sua decisão tinha um trabalho e ainda solicitou suporte técnico." },
    { id: "s24", category: "SAVAGE", text: "Você faz problemas simples parecerem finais de temporada." },
    { id: "s25", category: "SAVAGE", text: "O sapo abaixou suas expectativas e ouviu a porta de um porão se abrir." },
    { id: "s26", category: "SAVAGE", text: "Você tem o raro talento de chegar à resposta errada de todas as direções." },
    { id: "s27", category: "SAVAGE", text: "Seu plano era mantido por confiança e um clipe de papel suspeito." },
    { id: "s28", category: "SAVAGE", text: "Você é o que acontece quando o tutorial é pulado com entusiasmo." },
    { id: "s29", category: "SAVAGE", text: "O sapo tentou seguir sua lógica e precisou de assistência na estrada." },
    { id: "s30", category: "SAVAGE", text: "Você não escolheu apenas a opção errada. Você inventou uma pior." },
    { id: "t01", category: "RARE_TRUTH", text: "Tomar uma decisão ruim não faz de você um idiota. Recusar-se a examiná-la pode fazer. Aprenda o que aconteceu, mude o padrão e continue." },
    { id: "t02", category: "RARE_TRUTH", text: "Inteligência não é a ausência de erros. É a capacidade de notá-los antes que o orgulho os transforme em hábitos." },
    { id: "t03", category: "RARE_TRUTH", text: "Você pode não precisar de um insulto. Você pode precisar de mais informações, mais paciência ou a coragem de admitir que sua primeira ideia estava errada." },
    { id: "t04", category: "RARE_TRUTH", text: "Um momento de tolice é temporário. Construir sua identidade em torno disso é opcional." },
    { id: "t05", category: "RARE_TRUTH", text: "Questionar a si mesmo geralmente é evidência de autoconsciência. Só não deixe que a autoconsciência se torne uma punição sem fim." },
    { id: "t06", category: "RARE_TRUTH", text: "Antes de se chamar de estúpido, pergunte-se se você estava cansado, apressado, desinformado, com medo ou tentando algo difícil pela primeira vez." },
    { id: "t07", category: "RARE_TRUTH", text: "Uma pessoa inteligente pode defender uma ideia ruim por muito tempo. A sabedoria começa quando estar correto importa mais do que parecer correto." },
    { id: "t08", category: "RARE_TRUTH", text: "Você tem permissão para mudar de ideia quando as evidências mudam. Isso não é fraqueza; é manutenção." },
    { id: "t09", category: "RARE_TRUTH", text: "O constrangimento geralmente é o preço de aprender em público. Pague uma vez, guarde a lição e siga em frente." },
    { id: "t10", category: "RARE_TRUTH", text: "A pergunta útil não é se você pareceu tolo. É se você entende o suficiente agora para escolher de forma diferente da próxima vez." },
    { id: "t11", category: "RARE_TRUTH", text: "A confiança sem curiosidade torna-se arrogância. Curiosidade sem ação torna-se evitação. Você precisa de um pouco de ambos." },
    { id: "t12", category: "RARE_TRUTH", text: "Às vezes a resposta madura é simplesmente: eu não sabia, estava errado e consertarei o que puder." },
    { id: "f01", category: "FATAL", text: "O sapo chegou a uma conclusão final." },
    { id: "f02", category: "FATAL", text: "Seu período de teste para o bom senso expirou." },
    { id: "f03", category: "FATAL", text: "O oráculo selecionou o realojamento permanente." },
    { id: "f04", category: "FATAL", text: "Este resultado não pode ser apelado." },
    { id: "f05", category: "FATAL", text: "Inteligência não encontrada. Removendo observador." },
    { id: "f06", category: "FATAL", text: "O sapo revisou suas escolhas e selecionou a saída de emergência." },
    { id: "f07", category: "FATAL", text: "O bom senso deixou o prédio. Você ainda está dentro." },
    { id: "f08", category: "FATAL", text: "O oráculo não encontrou dados recuperáveis de tomada de decisão." }
  ],
  pl: [
    { id: "c01", category: "COMMON", text: "Prawdopodobnie, ale dowody wciąż się ładują." },
    { id: "c02", category: "COMMON", text: "Żaba prosi o drugą opinię." },
    { id: "c03", category: "COMMON", text: "Nie dziś. Po prostu wyglądasz podejrzanie." },
    { id: "c04", category: "COMMON", text: "Twoja ostatnia decyzja nie pomogła twojej sprawie." },
    { id: "c05", category: "COMMON", text: "Wykryto inteligencję. Sygnał niezwykle słaby." },
    { id: "c06", category: "COMMON", text: "Rada jest zdezorientowana, ale optymistyczna." },
    { id: "c07", category: "COMMON", text: "Nie jesteś idiotą. Jesteś niezaplanowanym eksperymentem." },
    { id: "c08", category: "COMMON", text: "Zapytaj ponownie po tym, jak udasz, że najpierw pomyślałeś." },
    { id: "c09", category: "COMMON", text: "Nie. To były po prostu bzdury najwyższej jakości." },
    { id: "c10", category: "COMMON", text: "Żaba twierdzi, że twoja gwarancja jest nadal ważna." },
    { id: "c11", category: "COMMON", text: "Zdałeś, ale tylko dlatego, że test był do góry nogami." },
    { id: "c12", category: "COMMON", text: "Twój mózg ma zaplanowaną przerwę na kawę." },
    { id: "c13", category: "COMMON", text: "Wyniki niejednoznaczne. Zrestartuj swój zdrowy rozsądek." },
    { id: "c14", category: "COMMON", text: "Działasz w ramach normalnej ludzkiej głupoty." },
    { id: "c15", category: "COMMON", text: "Odpowiedź jest ukryta za kółkiem ładowania." },
    { id: "c16", category: "COMMON", text: "Być może. Żaba zapomniała pytania w połowie." },
    { id: "c17", category: "COMMON", text: "Twój spryt jest obecnie w trybie samolotowym." },
    { id: "c18", category: "COMMON", text: "Sytuacja jest głupia. Pozostajesz pod obserwacją." },
    { id: "c19", category: "COMMON", text: "U ciebie wszystko w porządku. Jednak plan wymaga nadzoru." },
    { id: "c20", category: "COMMON", text: "Wykryto nieszkodliwą ilość idiotycznej energii." },
    { id: "c21", category: "COMMON", text: "Żaba widzi potencjał. Odmawia jednak powiedzenia jakiego rodzaju." },
    { id: "c22", category: "COMMON", text: "Twój proces myślowy wybrał drogę widokową." },
    { id: "c23", category: "COMMON", text: "Nie mylisz się. Rzeczywistość bywa po prostu trudna." },
    { id: "c24", category: "COMMON", text: "Twój pomysł ma charakter. Dokładność nie została zaproszona." },
    { id: "c25", category: "COMMON", text: "Żaba kiwa uprzejmie głową i zmienia temat." },
    { id: "c26", category: "COMMON", text: "Twój mózg ma otwarte 37 kart, a gdzieś w tle leci muzyka." },
    { id: "c27", category: "COMMON", text: "Nie znaleziono idioty. Sprawdź ponownie po kolejnym zakupie." },
    { id: "c28", category: "COMMON", text: "Jesteś tymczasowo zwolniony z powodu niskich oczekiwań." },
    { id: "c29", category: "COMMON", text: "To nie była głupota. To było eksperymentalne podejmowanie decyzji." },
    { id: "c30", category: "COMMON", text: "Żaba nie może cię ocenić, kiedy tak bardzo się śmieje." },
    { id: "c31", category: "COMMON", text: "Twoja logika dotarła bezpiecznie. Twój wniosek przegapił autobus." },
    { id: "c32", category: "COMMON", text: "Z tej odległości wydajesz się w miarę funkcjonalny." },
    { id: "c33", category: "COMMON", text: "Werdykt brzmi: może, z dekoracyjną pewnością siebie." },
    { id: "c34", category: "COMMON", text: "Oczyszczono cię z zarzutów o celową inteligencję." },
    { id: "c35", category: "COMMON", text: "Żaba w ciebie wierzy, ze względów podatkowych." },
    { id: "n01", category: "SNARKY", text: "Otwarłeś tę stronę dobrowolnie. Zaczynajmy od tego." },
    { id: "n02", category: "SNARKY", text: "Żaba wierzyła w ciebie. Czas przeszły." },
    { id: "n03", category: "SNARKY", text: "Twój mózg wszedł w tryb oszczędzania energii." },
    { id: "n04", category: "SNARKY", text: "Myślisz poza szablonami tylko dlatego, że zgubiłeś szablon." },
    { id: "n05", category: "SNARKY", text: "To była odważna decyzja jak na kogoś bez planu." },
    { id: "n06", category: "SNARKY", text: "Nawet twój wymyślony doradca właśnie zrezygnował." },
    { id: "n07", category: "SNARKY", text: "Wygląda na to, że buforujesz się w prawdziwym życiu." },
    { id: "n08", category: "SNARKY", text: "Twój zdrowy rozsądek opuścił czat grupowy." },
    { id: "n09", category: "SNARKY", text: "Przyniosłeś pewność siebie na pojedynek na wiedzę." },
    { id: "n10", category: "SNARKY", text: "Plan był bez zarzutu, dopóki nie zderzył się z rzeczywistością." },
    { id: "n11", category: "SNARKY", text: "Twój wewnętrzny kompas jest sponsorowany przez chaos." },
    { id: "n12", category: "SNARKY", text: "Znowu pomyliłeś entuzjazm z przygotowaniem." },
    { id: "n13", category: "SNARKY", text: "Żaba sprawdziła twoje źródła. To były tylko domysły." },
    { id: "n14", category: "SNARKY", text: "Pominąłeś krok pierwszy i wymyśliłeś krok siódmy." },
    { id: "n15", category: "SNARKY", text: "Twój plan awaryjny to po prostu oryginalny plan, ale w czapce." },
    { id: "n16", category: "SNARKY", text: "To wyjaśnienie wywołało więcej pytań niż odpowiedzi." },
    { id: "n17", category: "SNARKY", text: "Jesteś o jedno pewne siebie kliknięcie od przymusowego samouczka." },
    { id: "n18", category: "SNARKY", text: "Żaba zaleca przeczytanie przycisku przed jego naciśnięciem." },
    { id: "n19", category: "SNARKY", text: "Twoja logika jest technicznie obecna, ale emocjonalnie niedostępna." },
    { id: "n20", category: "SNARKY", text: "Rozwiązałeś niewłaściwy problem z imponującym zaangażowaniem." },
    { id: "n21", category: "SNARKY", text: "Twoje drzewo decyzyjne to bardziej krzew ozdobny." },
    { id: "n22", category: "SNARKY", text: "Dowody są jasne. Niestety, zignorowałeś je." },
    { id: "n23", category: "SNARKY", text: "Zrobiłeś własny reaserch i przestraszyłeś sam reaserch." },
    { id: "n24", category: "SNARKY", text: "Twoja pewność siebie wyrabia nadgodziny za darmo." },
    { id: "n25", category: "SNARKY", text: "Żaba gratuluje ci prawie zauważenia rzeczy oczywistych." },
    { id: "n26", category: "SNARKY", text: "Twój mózg zobaczył ostrzeżenie i potraktował je jako wyzwanie." },
    { id: "n27", category: "SNARKY", text: "Nie tylko minąłeś się z celem. Wystrzeliłeś go do innej strefy czasowej." },
    { id: "n28", category: "SNARKY", text: "Żaba poprosiła o twoje powody. Przedstawiłeś wzruszenie ramionami." },
    { id: "n29", category: "SNARKY", text: "Twój mózg kliknął 'przypomnij mi później' w odniesieniu do rzeczywistości." },
    { id: "n30", category: "SNARKY", text: "Nawet autokorekta odmawia wzięcia odpowiedzialności za tę decyzję." },
    { id: "n31", category: "SNARKY", text: "Nie myślisz poza schematami. Kłócisz się z opakowaniem." },
    { id: "n32", category: "SNARKY", text: "Sprawiasz, że spojrzenie w przeszłość wygląda jak zaawansowana technologia." },
    { id: "n33", category: "SNARKY", text: "Twoja logika została wycofana z powodu braku zainteresowania." },
    { id: "n34", category: "SNARKY", text: "Żaba widziała lepsze planowanie u przeglądarki z czterdziestoma wyskakującymi oknami." },
    { id: "n35", category: "SNARKY", text: "Wszedłeś do labiryntu, zignorowałeś mapę i zrzuciłeś winę na ściany." },
    { id: "n36", category: "SNARKY", text: "Twój zdrowy rozsądek widnieje obecnie jako zaginiony." },
    { id: "n37", category: "SNARKY", text: "Jesteś ludzką wersją klikania 'Akceptuj' bez czytania czegokolwiek." },
    { id: "s01", category: "SAVAGE", text: "To przez ciebie instrukcje zawierają obrazki." },
    { id: "s02", category: "SAVAGE", text: "Twoja strategia ma integralność strukturalną mokrego chleba." },
    { id: "s03", category: "SAVAGE", text: "Żaba przejrzała twoje opcje i zażądała dodatku za pracę w szkodliwych warunkach." },
    { id: "s04", category: "SAVAGE", text: "Ty nie popełniasz błędów. Tworzysz rozszerzone uniwersa filmowe." },
    { id: "s05", category: "SAVAGE", text: "Twój tok myślenia został zastąpiony przez komunikację miejską." },
    { id: "s06", category: "SAVAGE", text: "Pomyślnie oblałeś samouczek." },
    { id: "s07", category: "SAVAGE", text: "Wszechświat dał ci wolną wolę i natychmiast pożałował tej funkcji." },
    { id: "s08", category: "SAVAGE", text: "Mógłbyś zdezorientować kompas stojąc w miejscu." },
    { id: "s09", category: "SAVAGE", text: "Twój plan ma mniej działających części niż zepsuta łyżka." },
    { id: "s10", category: "SAVAGE", text: "Żaba znalazła twoją logikę w biurze rzeczy znalezionych. Nikt się po nią nie zgłosił." },
    { id: "s11", category: "SAVAGE", text: "Zmieniłeś prosty problem w płatny dodatek DLC." },
    { id: "s12", category: "SAVAGE", text: "Twój dobry pomysł uciekł, zanim zdążyłeś go wyjaśnić." },
    { id: "s13", category: "SAVAGE", text: "Przechodzisz konsekwencje na czas bez użycia mapy." },
    { id: "s14", category: "SAVAGE", text: "Twój mózg przesłał zadanie w niewłaściwym formacie pliku." },
    { id: "s15", category: "SAVAGE", text: "Wnosisz unikalną perspektywę: zawsze z niewłaściwego kierunku." },
    { id: "s16", category: "SAVAGE", text: "Twój proces decyzyjny to escape room bez wyjścia." },
    { id: "s17", category: "SAVAGE", text: "Masz pewność siebie aktualizacji systemu operacyjnego w najgorszym możliwym momencie." },
    { id: "s18", category: "SAVAGE", text: "Żaba próbowała obniżyć poprzeczkę. Ty przyniosłeś łopatę." },
    { id: "s19", category: "SAVAGE", text: "Mógłbyś przegrać kłótnię z drzwiami automatycznymi." },
    { id: "s20", category: "SAVAGE", text: "Twój ostatni dobry pomysł zgłosił zaginięcie." },
    { id: "s21", category: "SAVAGE", text: "Żaba znalazła więcej strategii w kalkulatorze bez baterii." },
    { id: "s22", category: "SAVAGE", text: "Jakoś udało ci się zmienić nierobienie niczego w wieloetapową porażkę." },
    { id: "s23", category: "SAVAGE", text: "Twoja decyzja miała jedno zadanie, a i tak poprosiła o wsparcie techniczne." },
    { id: "s24", category: "SAVAGE", text: "Sprawiasz, że proste problemy wydają się jak finały sezonu." },
    { id: "s25", category: "SAVAGE", text: "Żaba obniżyła swoje oczekiwania i usłyszała otwierające się drzwi do piwnicy." },
    { id: "s26", category: "SAVAGE", text: "Masz rzadki talent docierania do złej odpowiedzi ze wszystkich kierunków." },
    { id: "s27", category: "SAVAGE", text: "Twój plan trzymał się na pewności siebie i jednym podejrzanym spinaczu." },
    { id: "s28", category: "SAVAGE", text: "Jesteś tym, co się dzieje, gdy z entuzjazmem pomija się instrukcję." },
    { id: "s29", category: "SAVAGE", text: "Żaba próbowała podążać za twoją logiką i potrzebowała pomocy drogowej." },
    { id: "s30", category: "SAVAGE", text: "Nie tylko wybrałeś złą opcję. Wymyśliłeś jeszcze gorszą." },
    { id: "t01", category: "RARE_TRUTH", text: "Podjęcie jednej złej decyzji nie czyni cię idiotą. Odmowa jej przeanalizowania już tak. Wyciągnij wnioski, zmień wzorzec i idź dalej." },
    { id: "t02", category: "RARE_TRUTH", text: "Inteligencja to nie brak błędów. To umiejętność zauważania ich zanim duma zmieni je w nawyki." },
    { id: "t03", category: "RARE_TRUTH", text: "Być może nie potrzebujesz obelgi. Być może potrzebujesz więcej informacji, cierpliwości lub odwagi, by przyznać, że twój pierwszy pomysł był zły." },
    { id: "t04", category: "RARE_TRUTH", text: "Chwila głupoty jest tymczasowa. Budowanie wokół niej swojej tożsamości jest opcjonalne." },
    { id: "t05", category: "RARE_TRUTH", text: "Kwestionowanie siebie zazwyczaj świadczy o samoświadomości. Tylko nie pozwól, by samoświadomość stała się niekończącym się karaniem siebie." },
    { id: "t06", category: "RARE_TRUTH", text: "Zanim nazwiesz się głupim, zadaj sobie pytanie, czy byłeś zmęczony, spieszyłeś się, brakowało ci informacji, bałeś się, czy próbowałeś czegoś trudnego po raz pierwszy." },
    { id: "t07", category: "RARE_TRUTH", text: "Inteligentna osoba potrafi bronić złego pomysłu przez bardzo długi czas. Mądrość zaczyna się, gdy posiadanie racji znaczy więcej niż wyglądanie, jakby się ją miało." },
    { id: "t08", category: "RARE_TRUTH", text: "Masz prawo zmienić zdanie, gdy zmienią się dowody. To nie jest słabość; to konserwacja twojego umysłu." },
    { id: "t09", category: "RARE_TRUTH", text: "Wstyd to często cena uczenia się w obecności innych. Zapłać ją raz, zachowaj lekcję i ruszaj naprzód." },
    { id: "t10", category: "RARE_TRUTH", text: "Przydatne pytanie nie brzmi, czy wyglądałeś głupio. Brzmi ono, czy teraz rozumiesz wystarczająco dużo, by następnym razem wybrać inaczej." },
    { id: "t11", category: "RARE_TRUTH", text: "Pewność siebie bez ciekawości staje się arogancją. Ciekawość bez działania staje się unikaniem. Potrzebujesz trochę obu." },
    { id: "t12", category: "RARE_TRUTH", text: "Czasami dojrzałą reakcją jest po prostu: nie wiedziałem, myliłem się i naprawię to, co mogę." },
    { id: "f01", category: "FATAL", text: "Żaba podjęła ostateczną decyzję." },
    { id: "f02", category: "FATAL", text: "Twój okres próbny na zdrowy rozsądek wygasł." },
    { id: "f03", category: "FATAL", text: "Wyrocznia wybrała dla ciebie trwałą relokację." },
    { id: "f04", category: "FATAL", text: "Od tego wyniku nie ma odwołania." },
    { id: "f05", category: "FATAL", text: "Nie znaleziono inteligencji. Usuwanie obserwatora." },
    { id: "f06", category: "FATAL", text: "Żaba przejrzała twoje wybory i wybrała wyjście ewakuacyjne." },
    { id: "f07", category: "FATAL", text: "Zdrowy rozsądek opuścił budynek. Ty nadal jesteś w środku." },
    { id: "f08", category: "FATAL", text: "Wyrocznia nie znalazła żadnych danych decyzyjnych nadających się do odzyskania." }
  ]
});

export const CATEGORY_LABELS = Object.freeze({
  en: {
    COMMON: "MILDLY QUESTIONABLE",
    SNARKY: "THE FROG IS JUDGING",
    SAVAGE: "EMOTIONAL DAMAGE",
    RARE_TRUTH: "RARE TRUTH",
    FATAL: "FATAL ERROR",
  },
  es: {
    COMMON: "LIGERAMENTE CUESTIONABLE",
    SNARKY: "LA RANA TE ESTÁ JUZGANDO",
    SAVAGE: "DAÑO EMOCIONAL",
    RARE_TRUTH: "VERDAD RARA",
    FATAL: "ERROR FATAL",
  },
  pt: {
    COMMON: "LEVEMENTE QUESTIONÁVEL",
    SNARKY: "O SAPO ESTÁ JULGANDO",
    SAVAGE: "DANO EMOCIONAL",
    RARE_TRUTH: "VERDADE RARA",
    FATAL: "ERRO FATAL",
  },
  pl: {
    COMMON: "LEKKO WĄTPLIWE",
    SNARKY: "ŻABA CIĘ OCENIA",
    SAVAGE: "EMOCJONALNE OBRAŻENIA",
    RARE_TRUTH: "RZADKA PRAWDA",
    FATAL: "BŁĄD FATALNY",
  }
});
