export const ANSWERS = Object.freeze([
  // COMMON — 35
  { id: "c01", category: "COMMON", text: "Probably, but the evidence is still loading." },
  { id: "c02", category: "COMMON", text: "The frog requests a second opinion." },
  { id: "c03", category: "COMMON", text: "Not today. You merely look suspicious." },
  { id: "c04", category: "COMMON", text: "Your last decision did not help your case." },
  { id: "c05", category: "COMMON", text: "Intelligence detected. Signal extremely weak." },
  { id: "c06", category: "COMMON", text: "The council is confused, but optimistic." },
  { id: "c07", category: "COMMON", text: "You are not an idiot. You are an unscheduled experiment." },
  { id: "c08", category: "COMMON", text: "Ask again after pretending to think first." },
  { id: "c09", category: "COMMON", text: "No. That was simply premium-grade nonsense." },
  { id: "c10", category: "COMMON", text: "The frog says your warranty is still valid." },
  { id: "c11", category: "COMMON", text: "You pass, but only because the test was upside down." },
  { id: "c12", category: "COMMON", text: "Your brain is on a scheduled coffee break." },
  { id: "c13", category: "COMMON", text: "Results inconclusive. Please reboot your common sense." },
  { id: "c14", category: "COMMON", text: "You are operating within normal human silliness." },
  { id: "c15", category: "COMMON", text: "The answer is hidden behind a loading spinner." },
  { id: "c16", category: "COMMON", text: "Maybe. The frog forgot the question halfway through." },
  { id: "c17", category: "COMMON", text: "Your cleverness is currently in airplane mode." },
  { id: "c18", category: "COMMON", text: "The situation is silly. You remain under investigation." },
  { id: "c19", category: "COMMON", text: "You are fine. The plan, however, needs supervision." },
  { id: "c20", category: "COMMON", text: "A harmless amount of idiot energy has been detected." },
  { id: "c21", category: "COMMON", text: "The frog sees potential. It refuses to say what kind." },
  { id: "c22", category: "COMMON", text: "Your thought process took the scenic route." },
  { id: "c23", category: "COMMON", text: "You are not wrong. Reality is being difficult." },
  { id: "c24", category: "COMMON", text: "Your idea has character. Accuracy was not invited." },
  { id: "c25", category: "COMMON", text: "The frog nods politely and changes the subject." },
  { id: "c26", category: "COMMON", text: "Your brain has 37 tabs open and music playing somewhere." },
  { id: "c27", category: "COMMON", text: "No idiot found. Check again after your next purchase." },
  { id: "c28", category: "COMMON", text: "You are temporarily exempt due to low expectations." },
  { id: "c29", category: "COMMON", text: "That was not stupidity. It was experimental decision-making." },
  { id: "c30", category: "COMMON", text: "The frog cannot judge you while laughing this hard." },
  { id: "c31", category: "COMMON", text: "Your logic arrived safely. Your conclusion missed the bus." },
  { id: "c32", category: "COMMON", text: "You appear mostly functional from this distance." },
  { id: "c33", category: "COMMON", text: "The verdict is maybe, with decorative confidence." },
  { id: "c34", category: "COMMON", text: "You have been cleared of intentional intelligence." },
  { id: "c35", category: "COMMON", text: "The frog believes in you, for tax purposes." },

  // SNARKY — 25
  { id: "n01", category: "SNARKY", text: "You opened this website voluntarily. Let us begin there." },
  { id: "n02", category: "SNARKY", text: "The frog had faith in you. Past tense." },
  { id: "n03", category: "SNARKY", text: "Your brain has entered energy-saving mode." },
  { id: "n04", category: "SNARKY", text: "You are thinking outside the box because you lost the box." },
  { id: "n05", category: "SNARKY", text: "That was a brave decision for someone without a plan." },
  { id: "n06", category: "SNARKY", text: "Even your imaginary advisor just resigned." },
  { id: "n07", category: "SNARKY", text: "You appear to be buffering in real life." },
  { id: "n08", category: "SNARKY", text: "Your common sense has left the group chat." },
  { id: "n09", category: "SNARKY", text: "You brought confidence to a knowledge fight." },
  { id: "n10", category: "SNARKY", text: "The plan was flawless until it encountered reality." },
  { id: "n11", category: "SNARKY", text: "Your internal compass is sponsored by chaos." },
  { id: "n12", category: "SNARKY", text: "You have mistaken enthusiasm for preparation again." },
  { id: "n13", category: "SNARKY", text: "The frog checked your sources. They were vibes." },
  { id: "n14", category: "SNARKY", text: "You skipped step one and invented step seven." },
  { id: "n15", category: "SNARKY", text: "Your backup plan is just the original plan wearing a hat." },
  { id: "n16", category: "SNARKY", text: "That explanation raised more questions than it buried." },
  { id: "n17", category: "SNARKY", text: "You are one confident click away from a tutorial." },
  { id: "n18", category: "SNARKY", text: "The frog recommends reading the button before pressing it." },
  { id: "n19", category: "SNARKY", text: "Your logic is technically present and emotionally unavailable." },
  { id: "n20", category: "SNARKY", text: "You solved the wrong problem with impressive dedication." },
  { id: "n21", category: "SNARKY", text: "Your decision tree is more of a decorative shrub." },
  { id: "n22", category: "SNARKY", text: "The evidence is clear. Unfortunately, you ignored it." },
  { id: "n23", category: "SNARKY", text: "You did your own research and frightened the research." },
  { id: "n24", category: "SNARKY", text: "Your confidence is doing unpaid overtime." },
  { id: "n25", category: "SNARKY", text: "The frog says congratulations on almost noticing the obvious." },

  // SAVAGE — 18
  { id: "s01", category: "SAVAGE", text: "You are the reason instructions include pictures." },
  { id: "s02", category: "SAVAGE", text: "Your strategy has all the structural integrity of wet bread." },
  { id: "s03", category: "SAVAGE", text: "The frog reviewed your choices and requested hazard pay." },
  { id: "s04", category: "SAVAGE", text: "You do not make mistakes. You create extended cinematic universes." },
  { id: "s05", category: "SAVAGE", text: "Your train of thought has been replaced by a bus service." },
  { id: "s06", category: "SAVAGE", text: "You have successfully failed the tutorial." },
  { id: "s07", category: "SAVAGE", text: "The universe gave you free will and immediately regretted the feature." },
  { id: "s08", category: "SAVAGE", text: "You could confuse a compass by standing still." },
  { id: "s09", category: "SAVAGE", text: "Your plan has fewer working parts than a broken spoon." },
  { id: "s10", category: "SAVAGE", text: "The frog found your logic in the lost-and-found. Nobody claimed it." },
  { id: "s11", category: "SAVAGE", text: "You turned a simple problem into downloadable content." },
  { id: "s12", category: "SAVAGE", text: "Your good idea escaped before you could explain it." },
  { id: "s13", category: "SAVAGE", text: "You are speedrunning consequences with no map." },
  { id: "s14", category: "SAVAGE", text: "Your brain submitted the assignment in the wrong file format." },
  { id: "s15", category: "SAVAGE", text: "You bring a unique perspective: consistently from the wrong direction." },
  { id: "s16", category: "SAVAGE", text: "Your decision-making process is an escape room with no exit." },
  { id: "s17", category: "SAVAGE", text: "You have the confidence of a software update at the worst possible time." },
  { id: "s18", category: "SAVAGE", text: "The frog tried lowering the bar. You brought a shovel." },

  // RARE TRUTH — 12
  { id: "t01", category: "RARE_TRUTH", text: "Making one bad decision does not make you an idiot. Refusing to examine it might. Learn what happened, change the pattern, and continue." },
  { id: "t02", category: "RARE_TRUTH", text: "Intelligence is not the absence of mistakes. It is the ability to notice them before pride turns them into habits." },
  { id: "t03", category: "RARE_TRUTH", text: "You may not need an insult. You may need more information, more patience, or the courage to admit that your first idea was wrong." },
  { id: "t04", category: "RARE_TRUTH", text: "A foolish moment is temporary. Building your identity around it is optional." },
  { id: "t05", category: "RARE_TRUTH", text: "Questioning yourself is usually evidence of self-awareness. Just do not let self-awareness become endless self-punishment." },
  { id: "t06", category: "RARE_TRUTH", text: "Before calling yourself stupid, ask whether you were tired, rushed, uninformed, afraid, or trying something difficult for the first time." },
  { id: "t07", category: "RARE_TRUTH", text: "A smart person can defend a bad idea for a very long time. Wisdom begins when being correct matters more than looking correct." },
  { id: "t08", category: "RARE_TRUTH", text: "You are allowed to change your mind when the evidence changes. That is not weakness; it is maintenance." },
  { id: "t09", category: "RARE_TRUTH", text: "Embarrassment is often the price of learning in public. Pay it once, keep the lesson, and move forward." },
  { id: "t10", category: "RARE_TRUTH", text: "The useful question is not whether you looked foolish. It is whether you understand enough now to choose differently next time." },
  { id: "t11", category: "RARE_TRUTH", text: "Confidence without curiosity becomes arrogance. Curiosity without action becomes avoidance. You need a little of both." },
  { id: "t12", category: "RARE_TRUTH", text: "Sometimes the mature response is simply: I did not know, I was wrong, and I will fix what I can." },

  // FATAL — 5
  { id: "f01", category: "FATAL", text: "The frog has reached a final conclusion." },
  { id: "f02", category: "FATAL", text: "Your trial period for common sense has expired." },
  { id: "f03", category: "FATAL", text: "The oracle has selected permanent relocation." },
  { id: "f04", category: "FATAL", text: "This result cannot be appealed." },
  { id: "f05", category: "FATAL", text: "Intelligence not found. Removing observer." },
]);

export const CATEGORY_LABELS = Object.freeze({
  COMMON: "MILDLY QUESTIONABLE",
  SNARKY: "THE FROG IS JUDGING",
  SAVAGE: "EMOTIONAL DAMAGE",
  RARE_TRUTH: "RARE TRUTH",
  FATAL: "FATAL ERROR",
});
